# Generated by Django 5.1.15 on 2026-06-18 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_issue_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='idx_issue_status_time'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['user', 'status'], name='idx_pr_user_status'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['issue', 'status'], name='idx_pr_issue_status'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_pr_status_time'),
        ),
    ]
