# Generated by Django 5.0.14 on 2026-07-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0017_merge_20260716_1436"),
        ("sandbox", "0017_triageissue_triageattempt"),
        ("sandbox", "0018_merge_20260716_1841"),
        ("sandbox", "0018_merge_20260716_1849"),
    ]

    operations = []
