# Generated by Django 5.0.14 on 2026-07-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0021_adrscenario_alter_triageattempt_label_score_and_more'),
        ('sandbox', '0021_alter_triageattempt_label_score_and_more'),
    ]

    operations = [
    ]
