# Generated by Django 5.0.14 on 2026-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_content_type_ossissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='gitlab_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
