# Generated by Django 5.1.15 on 2026-06-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_certificate_is_active'),
        ('progress', '0007_lessonprogress_attempt_count'),
    ]

    operations = [
    ]
