# Generated by Django 5.1.15 on 2026-06-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_helprequest_status'),
        ('progress', '0008_merge_20260614_0948'),
        ('progress', '0009_badge_category_badge_icon_asset_url'),
    ]

    operations = [
    ]
