# Generated by Django 5.1.15 on 2026-06-18 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_merge_20260618_0824'),
        ('progress', '0010_merge_20260618_0833'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'exercise', 'is_correct'], name='idx_ex_attempt_user_correct'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', '-created_at'], name='idx_ex_attempt_user_time'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['user', 'status'], name='idx_help_req_user_status'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_help_req_status_time'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', '-updated_at'], name='idx_progress_user_updated'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'is_correct'], name='idx_quiz_user_correct'),
        ),
    ]
