# Generated by Django 5.1.15 on 2026-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_lesson_estimated_minutes'),
        ('content', '0003_lesson_category_alter_lesson_estimated_minutes'),
    ]

    operations = [
    ]
