name: Documentation
description: Propose improvements or fixes to project documentation
title: '[DOCS]: '
labels:
  - documentation
body:
  - type: textarea
    id: description
    attributes:
      label: Documentation Description
      description: Describe what documentation needs to be added or updated.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Affected Files or Sections
      description: Mention specific doc files or README sections affected.
    validations:
      required: false
