name: Feature Request
description: Suggest an idea or new feature for the project
title: '[FEAT]: '
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the proposed feature.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement / Motivation
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working.
    validations:
      required: true
