<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-06-30 15:00

from django.db import migrations, models
=======
# Generated by Django 5.1.15 on 2026-06-30 05:33

from django.db import migrations
>>>>>>> upstream/main


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_merge_20260628_0919"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
<<<<<<< HEAD
=======
            name="dnd_enabled",
        ),
        migrations.RemoveField(
            model_name="userprofile",
>>>>>>> upstream/main
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="theme_preference",
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User bio in Markdown.",
                max_length=1500,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio_html",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dnd_enabled",
            field=models.BooleanField(default=False),
        ),
=======
>>>>>>> upstream/main
    ]
